[package]
name = "goscript-codegen"
version = "0.1.0"
authors = ["oxfeeefeee <pb01005051@gmail.com>"]
edition = "2021"

[features] 
default = []
async = ["goscript-vm/async"]  

[dependencies]

[dependencies.goscript-parser]
path = "../parser"
version = "0.1.0"

[dependencies.goscript-vm]
path = "../vm"
version = "0.1.0"

[dependencies.goscript-types]
path = "../types"
version = "0.1.0"

[dev-dependencies]
time-test = "0.2.2"